name: Node.js CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local utee/udagram-frontend:v2
    - run: docker tag udagram-api-user utee/udagram-api-user:v1
    - run: docker tag udagram-api-feed utee/udagram-api-feed:v1
    - run: docker tag reverseproxy utee/reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push utee/udagram-frontend:v2
    - run: docker push utee/udagram-api-user:v1
    - run: docker push utee/udagram-api-feed:v1
    - run: docker push utee/reverseproxy:v1
